-- Create Products Table
CREATE TABLE Products (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductName VARCHAR2(100) NOT NULL,
    Category VARCHAR2(50) NOT NULL,
    Price NUMBER(10,2) CHECK (Price > 0),
    StockQuantity NUMBER DEFAULT 0 CHECK (StockQuantity >= 0)
);

-- Create Customers Table
CREATE TABLE Customers (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(50) NOT NULL,
    LastName VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Phone VARCHAR2(15)
);

-- Create Orders Table
CREATE TABLE Orders (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER NOT NULL,
    OrderDate DATE DEFAULT SYSDATE,
    TotalAmount NUMBER(10,2) DEFAULT 0 CHECK (TotalAmount >= 0),
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

-- Create OrderDetails Table
CREATE TABLE OrderDetails (
    OrderDetailID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID NUMBER NOT NULL,
    ProductID NUMBER NOT NULL,
    Quantity NUMBER CHECK (Quantity > 0),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);
-- Insert Products
INSERT INTO Products (ProductName, Category, Price, StockQuantity)
VALUES ('Laptop', 'Electronics', 75000, 50);
INSERT INTO Products (ProductName, Category, Price, StockQuantity)
VALUES ('Headphones', 'Accessories', 2500, 15);

-- Insert Customers
INSERT INTO Customers (FirstName, LastName, Email, Phone)
VALUES ('Aarav', 'Sharma', 'aarav.sharma@example.com', '9876543210');
INSERT INTO Customers (FirstName, LastName, Email, Phone)
VALUES ('Diya', 'Patel', 'diya.patel@example.com', '9988776655');

-- Insert Orders
INSERT INTO Orders (CustomerID, TotalAmount)
VALUES (1, 77500);
INSERT INTO Orders (CustomerID, TotalAmount)
VALUES (2, 5000);

-- Insert OrderDetails
INSERT INTO OrderDetails (OrderID, ProductID, Quantity)
VALUES (1, 1, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity)
VALUES (2, 2, 2);
